ALLOWED_EXTENSIONS_FILES = set(['txt', 'pdf', 'md', 'zip', 'tar', 'gz', 'docx', 'xlsx'])

FILETYPE_CHOICES = ['Binary', 'Scripts (Source code)', 'Readme', 'Other']

CATEGORY_LIST = set([
"Agile software development",
"Apps and app store analysis",
"Automated program repair",
"Autonomic and (self-)adaptive systems",
"Clones and change",
"Cloud computing",
"Code summarization",
"Component-based software engineering",
"Configuration management and deployment",
"Crowd sourced software engineering",
"Cyber physical systems",
"Debugging, fault localization, and repair",
"Dependability, safety, and reliability",
"DevOps",
"Distributed and collaborative software engineering",	
"Embedded software",
"Empirical software engineering",	
"End-user software engineering",
"Energy consumption",
"Formal methods",	
"Fuzzing",
"Green and sustainable technologies",
"Human and social aspects of software engineering",	
"Human-computer interaction",
"Machine learning and models",
"Middleware, frameworks, and APIs",	
"Mining software engineering repositories",
"Mobile applications",	
"Model-driven engineering",
"Parallel, distributed, and concurrent systems",	
"Performance",
"Program analysis",	
"Program comprehension",
"Program synthesis",	
"Programming languages",
"Recommendation systems",	
"Refactoring",
"Requirements engineering",	
"Reverse engineering",
"Search-based software engineering",	
"Security, privacy and trust",
"SE datasets, research infrastructure, and methodology",
"Software architecture",	
"Software economics and metrics",
"Software evolution and maintenance",	
"Software modeling and design",
"Software performance",	
"Software process",
"Software product lines",	
"Software reuse",
"Software services",	
"Software testing",
"Software visualization",	
"Specification and modeling languages",
"Tools and environments",	
"Tool taxonomy and adoption",
"Traceability",
"Trends and challenges",
"Ubiquitous/pervasive software systems",
"Validation and verification",
"Web testing",
"Other"
])

icondict = {
  "Agile software development" : 1,
  "Apps and app store analysis" : 2,
  "Automated program repair" : 43,
  "Autonomic and (self-)adaptive systems" : 3,
  "Clones and change" : 38,
  "Cloud computing" : 4,
  "Code summarization" : 40,
  "Component-based software engineering" : 5,
  "Configuration management and deployment" : 6,
  "Crowd sourced software engineering" : 7,
  "Cyber physical systems" : 8,
  "Debugging, fault localization, and repair" : 9,
  "Dependability, safety, and reliability" : 10,
  "DevOps" : 42,
  "Distributed and collaborative software engineering" : 11,	
  "Embedded software" : 12,
  "Empirical software engineering" : 13,	
  "End-user software engineering" : 14,
  "Energy consumption" : 45,
  "Formal methods" : 15,	
  "Fuzzing" : 37,
  "Green and sustainable technologies" : 16,
  "Human and social aspects of software engineering" : 17,	
  "Human-computer interaction" : 18,
  "Machine learning and models" : 41,
  "Middleware, frameworks, and APIs" : 19,	
  "Mining software engineering repositories" : 20,
  "Mobile applications" : 21,	
  "Model-driven engineering" : 22,
  "Parallel, distributed, and concurrent systems" : 23,	
  "Performance" : 24,
  "Program analysis" : 25,	
  "Program comprehension" : 25,
  "Program synthesis" : 25,	
  "Programming languages" : 25,
  "Recommendation systems" : 26,	
  "Refactoring" : 27,
  "Requirements engineering" : 28,	
  "Reverse engineering" : 29,
  "Search-based software engineering" : 30,	
  "Security, privacy and trust" : 31,
  "SE datasets, research infrastructure, and methodology" : 46,
  "Software architecture" : 32,	
  "Software economics and metrics" : 32,
  "Software evolution and maintenance" : 32,	
  "Software modeling and design" : 32,
  "Software performance" : 32,	
  "Software process" : 32,
  "Software product lines" : 32,	
  "Software reuse" : 32,
  "Software services" : 32,	
  "Software testing" : 32,
  "Software visualization" : 32,	
  "Specification and modeling languages" : 25,
  "Tools and environments" : 33,
  "Tools taxonomy and adoption" : 33,
  "Traceability" : 34,
  "Trends and challenges" : 44,
  "Ubiquitous/pervasive software systems" : 35,
  "Validation and verification" : 31,
  "Web testing" : 39,
  "Other" : 36
}

