"""papers table

Revision ID: 050883b43dfa
Revises: 
Create Date: 2018-10-25 16:15:09.257317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '050883b43dfa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paper',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_name', sa.String(length=64), nullable=True),
    sa.Column('paper_name', sa.Text(), nullable=True),
    sa.Column('author_email', sa.String(length=120), nullable=True),
    sa.Column('tool_name', sa.String(length=200), nullable=True),
    sa.Column('tool_format', sa.String(length=64), nullable=True),
    sa.Column('link_to_pdf', sa.String(length=250), nullable=True),
    sa.Column('link_to_archive', sa.String(length=250), nullable=True),
    sa.Column('link_to_demo', sa.String(length=250), nullable=True),
    sa.Column('bibtex', sa.Text(), nullable=True),
    sa.Column('file_urls', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('paper')
    # ### end Alembic commands ###
