"""empty message

Revision ID: 17b07ccc30f2
Revises: cb25eca0d4ca
Create Date: 2018-12-18 15:40:36.788468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17b07ccc30f2'
down_revision = 'cb25eca0d4ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('filetype', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'filetype')
    # ### end Alembic commands ###
