"""papers table

Revision ID: 2180d20fcfad
Revises: d85c430a7c1e
Create Date: 2018-10-11 21:09:17.583680

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2180d20fcfad'
down_revision = 'd85c430a7c1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('paper', 'link_to_readme')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paper', sa.Column('link_to_readme', mysql.VARCHAR(length=250), nullable=True))
    # ### end Alembic commands ###
