"""empty message

Revision ID: 507b93b09f73
Revises: ee1eb38566c5
Create Date: 2018-12-17 13:43:49.010583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '507b93b09f73'
down_revision = 'ee1eb38566c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tag_tagname', table_name='tag')
    op.create_index(op.f('ix_tag_tagname'), 'tag', ['tagname'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tag_tagname'), table_name='tag')
    op.create_index('ix_tag_tagname', 'tag', ['tagname'], unique=False)
    # ### end Alembic commands ###
