"""tags table

Revision ID: 71bd12082ce3
Revises: 7e3cf46dbcca
Create Date: 2018-12-17 12:59:51.374270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71bd12082ce3'
down_revision = '7e3cf46dbcca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tagname', sa.String(length=140), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tag_tagname'), 'tag', ['tagname'], unique=False)
    op.create_table('paper_to_tags',
    sa.Column('paper_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['paper_id'], ['paper.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('paper_to_tags')
    op.drop_index(op.f('ix_tag_tagname'), table_name='tag')
    op.drop_table('tag')
    # ### end Alembic commands ###
