"""empty message

Revision ID: 726006fa8153
Revises: 17b07ccc30f2
Create Date: 2018-12-28 00:00:09.186025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '726006fa8153'
down_revision = '17b07ccc30f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment_by_email', sa.String(length=120), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('upvoted', sa.Boolean(), nullable=True),
    sa.Column('verified', sa.Integer(), nullable=True),
    sa.Column('paper_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comments')
    # ### end Alembic commands ###
