"""papers table

Revision ID: 7e3cf46dbcca
Revises: 050883b43dfa
Create Date: 2018-10-29 17:12:55.521700

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7e3cf46dbcca'
down_revision = '050883b43dfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paper', sa.Column('link_to_tool_webpage', sa.String(length=250), nullable=True))
    op.add_column('paper', sa.Column('tags', sa.Text(), nullable=True))
    op.drop_column('paper', 'tool_format')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paper', sa.Column('tool_format', mysql.VARCHAR(length=64), nullable=True))
    op.drop_column('paper', 'tags')
    op.drop_column('paper', 'link_to_tool_webpage')
    # ### end Alembic commands ###
