"""papers table

Revision ID: c2e6834f2485
Revises: 2180d20fcfad
Create Date: 2018-10-13 18:18:09.962317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2e6834f2485'
down_revision = '2180d20fcfad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paper', sa.Column('file_urls', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('paper', 'file_urls')
    # ### end Alembic commands ###
