"""papers table

Revision ID: cb25eca0d4ca
Revises: 
Create Date: 2018-12-17 16:14:08.674793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb25eca0d4ca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('papers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_name', sa.String(length=64), nullable=True),
    sa.Column('paper_name', sa.Text(), nullable=True),
    sa.Column('author_email', sa.String(length=120), nullable=True),
    sa.Column('tool_name', sa.String(length=200), nullable=True),
    sa.Column('link_to_pdf', sa.String(length=250), nullable=True),
    sa.Column('link_to_archive', sa.String(length=250), nullable=True),
    sa.Column('link_to_tool_webpage', sa.String(length=250), nullable=True),
    sa.Column('link_to_demo', sa.String(length=250), nullable=True),
    sa.Column('bibtex', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tagname', sa.String(length=140), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tags_tagname'), 'tags', ['tagname'], unique=True)
    op.create_table('files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=140), nullable=True),
    sa.Column('paper_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_files_filename'), 'files', ['filename'], unique=False)
    op.create_table('paper_to_tags',
    sa.Column('paper_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('paper_to_tags')
    op.drop_index(op.f('ix_files_filename'), table_name='files')
    op.drop_table('files')
    op.drop_index(op.f('ix_tags_tagname'), table_name='tags')
    op.drop_table('tags')
    op.drop_table('papers')
    # ### end Alembic commands ###
