"""papers table

Revision ID: d85c430a7c1e
Revises: ced5419238d3
Create Date: 2018-10-08 15:21:43.721581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd85c430a7c1e'
down_revision = 'ced5419238d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paper', sa.Column('tool_format', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('paper', 'tool_format')
    # ### end Alembic commands ###
