"""empty message

Revision ID: e9f031d6a549
Revises: 73b9255b0757
Create Date: 2019-04-23 21:38:55.633221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9f031d6a549'
down_revision = '73b9255b0757'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('papers', sa.Column('conference', sa.String(length=200), nullable=True))
    op.add_column('papers', sa.Column('year', sa.String(length=4), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('papers', 'year')
    op.drop_column('papers', 'conference')
    # ### end Alembic commands ###
