"""empty message

Revision ID: ea6fadad6539
Revises: 726006fa8153
Create Date: 2019-01-04 16:07:15.654506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea6fadad6539'
down_revision = '726006fa8153'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('papers', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('papers', sa.Column('visibility', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('papers', 'visibility')
    op.drop_column('papers', 'description')
    # ### end Alembic commands ###
