"""empty message

Revision ID: ee1eb38566c5
Revises: 71bd12082ce3
Create Date: 2018-12-17 13:04:05.934491

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ee1eb38566c5'
down_revision = '71bd12082ce3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('paper', 'tags')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paper', sa.Column('tags', mysql.TEXT(), nullable=True))
    # ### end Alembic commands ###
